Cambiando los proceso de pos y pre instalación

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -14,18 +14,6 @@
 # Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
 # términos de la Licencia Pública General de GNU (versión 3).
 
-ERROR() {
-	printf "\033[1;31m${1}\033[0m\n"
-}
-
-ADVERTENCIA() {
-	printf "\033[1;33m${1}\033[0m\n"
-}
-
-EXITO() {
-	printf "\033[1;32m${1}\033[0m\n"
-}
-
 case ${1} in
 
 	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
@@ -36,7 +24,7 @@ case ${1} in
 			&& [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) -eq 1 ] \
 			&& [ -d "/home/${USERNAME}/.config" ] && [ -d "/home/${USERNAME}/Escritorio" ]; then
 
-				ADVERTENCIA 'Removiendo lanzador de escritorio para el usuario "'${USERNAME}'"'
+				echo 'Removiendo lanzador de escritorio para el usuario "'${USERNAME}'"'
 
 				# Removemos el lanzador
 				rm -rf /home/${USERNAME}/Escritorio/canaima-instalador.desktop
@@ -46,7 +34,7 @@ case ${1} in
 
 	*)
 
-		ERROR "postrm no reconoce el argumento '"${1}"'" >&2
+		echo "Error: postrm no reconoce el argumento '"${1}"'" >&2
 		exit 1
 	;;
 
